<?php 
$countPost = count($this->posts);
if( $this->infoSession->status == 'active' ):
include 'views/inc/header.php'; 
	
	/* CLASS NO POST */
	if( $countPost == 0 ) {
		$no_post_class = null;
	} else {
		$no_post_class = ' class="post-user-profile"';
	}
?>
<style>
	
	body
	{
		background-position: <?php echo $this->infoSession->bg_position; ?> 55px;
		background-attachment: <?php echo $this->infoSession->bg_attachment; ?>;
		
		<?php if( $this->infoSession->bg_attachment == 'fixed' ): ?>
		background-repeat: repeat repeat; 
		<?php else: ?>
		background-repeat: no-repeat; 
		<?php endif; ?>
		
		background-color: <?php echo $this->infoSession->bg_color; ?>;
		
		<?php if( $this->infoSession->bg != '' ): ?>
		background-image: url(<?php echo URL_BASE.'public/backgrounds/'.$this->infoSession->bg; ?>);
		<?php endif; ?>
	}
	
	body a,
	body a:hover { color: <?php echo $this->infoSession->color_link; ?>; }
	
	.icons { background-color: <?php echo $this->infoSession->color_link; ?>;}
	
</style>
<link href="<?php echo $_layoutParams['root_css']; ?>colorbox.css" rel="stylesheet" />
<link href="<?php echo $_layoutParams['root_css']; ?>jquery-ui-1.8.2.custom.css" rel="stylesheet" />
</head>
<!-- Body -->
	<body data-max="<?php echo MAX_LENGTH; ?>" data-accept="<?php echo $_SESSION['LANG']['accept']; ?>" data-cancel="<?php echo $_SESSION['LANG']['cancel']; ?>">
		<?php include 'views/inc/profile_summary_inc.php'; ?>
		<!-- warpper_top_bar -->
		<div class="warpper_top_bar">
				<!-- inner_top_bar -->
				<header class="inner_top_bar">
					<!-- padding_class -->
					<div class="padding_class">
						<?php include 'views/inc/logo.php'; ?>
					    <?php include 'views/inc/navigation.php'; ?>
			    </div><!-- padding_class -->
			</header><!-- inner_top_bar -->
		</div><!-- warpper_top_bar -->
	
	<!-- page -->
	<div class="page">
		<!-- layout -->
		<section class="layout session">
			<div class="popout"></div>
			<!-- padding_class -->
		    <div class="padding_class sessionClass">
		    	<div class="formSearchResp">
						   <form action="search/" class="formResponsive" method="get" id="search_engine" accept-charset="UTF-8">
							  <input id="btnItems" name="q" class="mention" type="text" placeholder="<?php echo $_SESSION['LANG']['search_word']; ?>" maxlength="100">	
						      </form>
					</div>
		    <!-- wrapper_grid -->
		     <div class="wrapper_grid floatLeft">
				   
				   <?php 
				   //<---- * profile_static * --->
				   include 'views/inc/profile_static.php'; 
				   
				   ?>
				   
				    <!-- Grid 1 -->
	   <div class="grid_1">
	   		<!-- container_grid -->
	   		<div class="container_grid">
				<div id="grid_post">
						<span class="grid_title_small"><?php echo $_SESSION['LANG']['what_new']; ?></span>
				   	<form style="border: none;" action="<?php echo URL_BASE; ?>public/ajax/upload.php" method="post" accept-charset="UTF-8" id="form_add_post" enctype="multipart/form-data">
					   <textarea name="add_post" class="post_add" id="add_post"></textarea>
						  <button data-title="<?php echo $_SESSION['LANG']['published_successfully']; ?>" id="button_add" <?php echo $no_post_class; ?> disabled="disabled" style="opacity: 0.5; cursor: default;" type="submit">
						  	<?php echo $_SESSION['LANG']['send']; ?>
						  	</button>
						    <input type="hidden" name="photoId" value="" id="photoId" />
						    
						    <div class="wrapper_media">
						    		<input type="file" id="upload" title="<?php echo $_SESSION['LANG']['upload_image']; ?>" class="typeFile" name="photo" accept="image/*" />
									<div class="video_post" title="<?php echo $_SESSION['LANG']['add_video']; ?>"></div>
									<div class="song_post" title="<?php echo $_SESSION['LANG']['add_song']; ?>"></div>
								</div><!-- wrapper_media -->
							
							
							<div id="counter"></div>
							<input type="text" name="video_link" id="video_link" placeholder="<?php echo $_SESSION['LANG']['link_videos']; ?>" value="" />
							<input type="text" name="song_link" id="song_link" placeholder="<?php echo $_SESSION['LANG']['link_song']; ?>" value="" />
						</form><!-- form -->
						
						<!-- Wrapper Preview -->
						<div id="wrapper_preview">
							<div id="container_preview">
							</div>
						</div><!-- Wrapper Preview -->
				 </div><!-- grid_post  -->	  
		    </div><!-- container_grid -->
		</div><!-- Grid 1  --> 
				   
				   <?php
				   //<---- * advertising * --->
				   include 'views/inc/advertising.php';
				   //<---- * who_follow * --->
				   include 'views/inc/who_to_follow.php';
				   //<---- * trending * --->
				   include 'views/inc/trending.php'; 
				    ?>
				   
				    <!-- Grid 1 -->
				   <div class="grid_1">
				   		<!-- container_grid -->
				   		<div class="container_grid about_pages">
				   			<?php include 'views/inc/footer_session.php'; ?>
				   		</div><!-- container_grid -->
				   </div><!-- Grid 1 -->
				   
				   
			   </div><!-- wrapper_grid -->
			   
			   <!-- Grid 2 -->
			   <div class="grid_2 floatRight">
			   <?php include 'views/inc/posts.php'; ?>
			    </div><!-- Grid 2 -->
			   		
			 </div><!-- padding_class -->
		</section><!-- layout -->
	</div><!-- page -->
	<div class="modal">
		<div id="content_modal">
		</div>
	</div>
	
	
   
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery-1.7.1.min.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery.easing.1.3.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery.placeholder.1.1.1.min.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery-ui-1.8.17.custom.min.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>functions.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>count.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>add.post.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery.form.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>timeago/jqueryTimeago_<?php echo $_SESSION['lang']; ?>.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery.colorbox.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>jquery.scroll.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>ajax.timeline.js"></script>
   <script src="<?php echo $_layoutParams['root_js']; ?>mentions.js"></script>
 
   <script type="text/javascript">
   
   $(".galeryAjax").colorbox({
   	fixed: false,
   	maxHeight: 550
   	});
   	
   <?php if( $countPost != 0 ): ?>

   $('.posts').scrollPagination({
		nop     : 10,
		offset  : 0,
		error   : '',
		delay   : 500,
		              
		scroll  : true, 
		query   : 0,
		file    : 'get_all_post.php',
		totalGlobal :  <?php echo $countPost; ?>
	});
	
	<?php endif; ?>
	
   jQuery(document).ready(function($) {

   //====== TIME AGO
	
   //=== COUNTER
   $('#add_post').live('hover', function(){
		if ($(this).data('hascharcount') == undefined) {
			$(this).data('hascharcount', true).charCount({ allowed: <?php echo MAX_LENGTH; ?>, warning: 10, css: 'counter_2' });
		}
		});
		
		$('#reply_post').live('hover', function(){
		if ($(this).data('hascharcount') == undefined) {
			$(this).data('hascharcount', true).charCount({ allowed: <?php echo MAX_LENGTH; ?>, warning: 10 });
		}
		});
  
  //=== PLACEHOLDER	
  $(function(){
      $(':input[placeholder]').placeholder();
    });
    
    
    //=================== * UPLOAD  * ===============//
    $('#upload').live('change', function(){     		 
	  $('<div id="loader_gif"></div>').insertBefore('#upload');
	  $('#button_add').attr({'disabled' : 'true'}).css({'opacity':'0.5','cursor':'default'});
	  $('#add_post').attr({'disabled' : 'true'}).css({'opacity':'0.5'});
					
			
			(function() {
	  		
	  		$("#form_add_post").ajaxForm({
	  		
	  		dataType : 'json',	
			success:  function(e)
			{
				if( e ) {
					$('#add_post').removeAttr('disabled').css({'opacity':'1'});
					if( e.error == 1 ) {
						$('#loader_gif').remove();
					}
					
					$('#wrapper_preview').show();
					$('#container_preview').html( ''+ e.output +'' ).show();
					$('#upload').val('');
					
					if( e.error == 0 ) {
						$('#loader_gif').css({background:'url("<?php echo URL_BASE; ?>thumb_fixed/30-30-tmp/'+ e.photo +'") center center no-repeat #FFF'}).addClass('deletePhoto').attr( 'data',e.photo ).attr( 'title','<?php echo $_SESSION['LANG']['delete_image']; ?>' );
						$('#wrapper_preview').show();
						$('#photoId').val(e.photo);
						$('#button_add').removeAttr('disabled').css({'opacity':'1','cursor':'pointer'});
					}
					
				} else {
					jAlert('<?php echo $_SESSION['LANG']['error']; ?>');
					$('#upload').val('');
					$('#button_add').removeAttr('disabled').css({'opacity':'1','cursor':'pointer'});
					$('#loader_gif').remove();
					
				}
			}//<----- SUCCESS
			
		}).submit();
		})(); //<--- FUNCTION %
	});//<--- LIVE
	
		//===== DELETE PHOTO
		$(".deletePhoto").live('click',function(){ 
					//=== PARAM
					var element     = $(this);
					var id          = element.attr("data");
					var info        = 'token_id=' + id;
					var add_post_   = $('#add_post').val();
					var video_link_ = $('#video_link').val();
								   		
					$.ajax({
					   type: "GET",
					   url: "<?php echo URL_BASE; ?>public/ajax/delete_id_photo.php",
					   data: info,
					   success: function(output){
					   if( output == 'TRUE' )
					   {
					   	if( add_post_ == 0 && video_link_ == 0 )
					   	{
					   		$('#button_add').attr({'disabled' : 'true'}).css({'opacity':'0.5','cursor':'default'});
					   	}
					   	
					   	$('#photoId').val('');
					   	element.fadeOut('fast',function(){
				   		  element.remove();
				   		});//<-- FUNCTION
					   }
					   
					 }
									
				});//<-- AJAX
			});//<--- CLICK
    
});//<-------- * DOM * ------>

  </script>
	</body>
</html>
  <?php
else:
	
	session_destroy();
    
	endif; ?>
   
